{% set name = "progress" %}
{% set version = "1.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1ba719f862ce885232a759eab47971fe74dfc7bb76ab8a51ef5940bad35086c

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
  run:
    - python

test:
  source_files:
    - test_progress.py
  requires:
    - pip
  commands:
    - pip check
    - python test_progress.py
  imports:
    - progress
    - progress.bar
    - progress.colors
    - progress.counter
    - progress.spinner

about:
  home: https://github.com/verigak/progress
  doc_url: https://github.com/verigak/progress/blob/master/README.rst
  dev_url: https://github.com/verigak/progress
  license: ISC
  license_family: MIT
  license_file: LICENSE
  summary: 'Easy progress reporting for Python'
  description: |
    progress is a lightweight and easy-to-use Python library 
    for displaying progress indicators in console applications.

extra:
  recipe-maintainers:
    - SoapZA
