travis:
  secure:
    BINSTAR_TOKEN: Uneu+5H7l0DXjkN1VFbrH3Gg2JU79swyZ9R9QV7Zn8blxnH/CCvIcObGUbiGgIILncseVizvng6tZOMG5zxDKPaiTtpePuEY0bLJXCAb3dy+eg+/0N7k+XACKsOPs52EHWbY0gyBgHqLhvU7A0t42prK/+uEdgt70Kck5nVkDqfnbsUnCYKs3djFcwLJpgTbdPm0/gXTJw0dXctCBoZ0iGCQb1XjP6UtepqiaEd6ruhfey4nDAmF31Y3MBSraqs3R9P0CGnqTAbrHQ4vCUe2t5KHRzqiDl4x3O7CcYD90xotq/6B8DAetHtU7JxRRkdC5Pctxr06c0WVJL9EsKFipKXNMqsB4KFCmH/Pps2fqNsRFCyyEYRJxjyZ2HgZ4aJgkyMWxD32XcaZdOo86UPvnWEEiDq/pT8/iu7ryPm5Qvqr4/Cd3HbKNkvIv5OArvOtPO1yLxQ/xrbBr++1DzCrcPa0UawfC4PzuMtRsxzeGiIb4C2PygtWA1oAVegMEe9caaRZlqevv4Pywta+NRfDu9hqNlJDqo+QXcBxkgKd8Qqfk9GJvf8P8rwC4PV9TbZjjsWiBFTkhXmVMAWhNrF6VdV6mVAmfU29i5uLKHye+DIVB7L75CEh7BLL6e2GWi+Ba+5RgL+vx5CJvlq/vNEToVWM26W3w3rkve5aqP86KFE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
